config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

#nest checkouts inside carts do/end to nest the routes
  resources :carts do
    resources :checkouts
  end

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
#A cart can have one or more checkouts downstream of it (although in this app it's not possible to have multiple checkouts per cart)
class Cart < ApplicationRecord
  has_many :checkouts , dependent: :destroy
end

app/models/checkout.rb
#Checkouts nested within Carts, to represent that a checkout is downstream of a cart in this flow
class Checkout < ApplicationRecord
  belongs_to :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  require 'rubygems'
  require 'braintree'
  require 'money'

#Localization for the Money gem
  Money.locale_backend = :i18n

  def index
    #Some definitions for summary stats in the carts#index view
    @carts = Cart.all
    @checkouts = Checkout.all
    @successfulCheckouts = Checkout.where.not(amount: nil)
  end

  def show
    #Helper definitions for info on individual checkouts in the carts#show view
    @cart = Cart.find(params[:id])
    @checkout = @cart.checkouts[0]
  end

  def create
    #Gateway and client token for hosted fields! and need to store the "cart" info in the db
    gateway = Braintree::Gateway.new(
      environment: :sandbox,
      merchant_id: 'hqk9y3rc8z3crhwg',
      public_key: '9sgptsv5sgw9kkjd',
      private_key: '31699066076e5a360797d6b8b8f5c28b'
    )
    @client_token = gateway.client_token.generate()
    @cart = Cart.new
    @cart.amount = params[:amount]
    @cart.save
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  require 'rubygems'
  require 'braintree'

  def transaction(gateway, amount, customer_id, device_data, sfs_bool)
    gateway.transaction.sale(
      amount: amount,
      customer_id: customer_id,
      device_data: device_data,
      options: {
        submit_for_settlement: sfs_bool
      }
    )
  end

  def vault(gateway, nonce, first_name, last_name, email, device_data, postal_code)
    gateway.customer.create(
      payment_method_nonce: nonce,
      first_name: first_name,
      last_name: last_name,
      email: email,
      device_data: device_data,
      credit_card: {
        billing_address: {
          first_name: first_name,
          last_name: last_name,
          postal_code: postal_code
        },
        options: {
          verify_card: 'true'
        }
      }
    )
  end

  def successResult(transaction_id)
    #Helper for creating confirmation page text
    @title = "Payment Confirmation"
    @message = "Payment Accepted! Transaction confirmation code " + transaction_id + ". Please print this page for your records."
    #Note that @link is an empty string for successful txns, as we are using @link to provide a link back to the welcome view to retry checkout for failed attempts
    @link = ""
  end

  def failureResult()
    #Helper for creating failed payment page text
    @title = "Payment Failed"
    @message = "Please provide another form of payment. "
    @link = "Click here to return to the checkout page."
  end

  def create
    #Gateway for txn.sale and customer.create
    gateway = Braintree::Gateway.new(
      environment: :sandbox,
      merchant_id: 'hqk9y3rc8z3crhwg',
      public_key: '9sgptsv5sgw9kkjd',
      private_key: '31699066076e5a360797d6b8b8f5c28b'
    )
    #New db row for the txn/customer info
    @checkout = Cart.find(params[:cart_id]).checkouts.new
    #Getting the card type from the tokenization payload
    @checkout.card_type = params[:card_type]
    customer_result = vault(gateway, params[:payment_method_nonce], params[:first_name], params[:last_name], params[:email], params[:data_collector], params[:postal_code])
    if customer_result.success?
      @checkout.verification_id = customer_result.customer.payment_methods[0].verification.id
      customer_id = customer_result.customer.id
      @checkout.customer_id = customer_id
      @checkout.postal_code = params[:postal_code]
      @checkout.email = params[:email]
      @checkout.first_name = params[:first_name]
      @checkout.last_name = params[:last_name]
      @checkout.verification_success = true
      @checkout.verification_result = "success"
      transaction_result = transaction(gateway, params[:amount], customer_id, params[:data_collector], true)
      if transaction_result.success?
        successResult(transaction_result.transaction.id)
        @checkout.transaction_id = transaction_result.transaction.id
        @checkout.transaction_success = true
        @checkout.transaction_result = "success"
        #Note that we wait to set the "amount" value until we know that the txn is successful.
        #This will come in handy for the way that I calculate summary statistics...
        @checkout.amount = params[:amount]
      else
        failureResult()
        #Checking that a transaction result exists before querying it to prevent errors.
        if transaction_result.respond_to?('transaction')
          @checkout.transaction_id = transaction_result.transaction.id
          @checkout.transaction_success = false
          if transaction_result.transaction.status == 'processor_declined'
            @checkout.transaction_result = "declined"
          elsif transaction_result.transaction.status == 'gateway_rejected'
            @checkout.transaction_result = "gateway rejected"
          else
            @checkout.transaction_result = "failed"
          end
        end
      end
    else
      failureResult()
      #Likewise, checking that a verification result exists before quering it to prevent errors.
      if customer_result.respond_to?('verification')
        @checkout.verification_success = false
        @checkout.verification_id = customer_result.verification.id
        if customer_result.verification.status == 'processor_declined'
          @checkout.verification_result = "declined"
        elsif customer_result.verification.status == 'gateway_rejected'
          @checkout.verification_result = "gateway rejected"
        else
          @checkout.verification_result = "failed"
        end
      end
    end
    @checkout.save
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  require 'rubygems'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/create.html.erb
<div id="main_wrapper">
      <div id="cart_container">
        <div id="title">Payment Details</div>
        <div id='form_container'>
          <!--Need to post to the checkouts#create route nested in the directory of the current cart-->
          <form action="/carts/<%= @cart.id %>/checkouts" id="hosted-fields-form" method="post">
                <label for="card-number">Card Number</label>
                <div id="card-number" class='hosted-field'></div>

                <label for="cvv">CVV</label>
                <div id="cvv" class='hosted-field'></div>

                <label for="expiration-date">Expiration Date</label>
                <div id="expiration-date" class='hosted-field'></div>

                <label for="postal_code">Postal Code</label>
                <input type='number' name='postal_code' id="postal_code" class='regular-field' required><br>

                <label for='first_name'>First Name</label><br>
                <input type='text' name='first_name' class='regular-field' id='first_name' required><br>

                <label for='last_name'>Last Name</label><br>
                <input type='text' name='last_name' class='regular-field' id='last_name' required><br>

                <label for='email'>Email</label><br>
                <input type='email' name='email' class='regular-field' id='email' required><br>

                <input type="submit" value="Pay" id='cart-submit' disabled />
                <input name='payment_method_nonce' id= 'payment_method_nonce' hidden >
                <input name='amount' id= 'amount' value="<%= @cart.amount %>" hidden >
                <input name='cart_id' id= 'cart_id' value="<%= @cart.id %>" hidden >
                <input name='card_type' id= 'card_type' hidden >
                <input name='data_collector' id= 'data_collector' hidden >
                <!--Line below required for Rails forms-->
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              </form>

        </div>
      </div>
  </div>

  <script src="https://js.braintreegateway.com/web/3.57.0/js/client.min.js"></script>
  <script src="https://js.braintreegateway.com/web/3.57.0/js/hosted-fields.min.js"></script>
  <script src="https://js.braintreegateway.com/web/3.57.0/js/data-collector.min.js"></script>

  <script>

      var form = document.querySelector('#hosted-fields-form');
      var submit = document.querySelector('input[type="submit"]');

      braintree.client.create({
        authorization: '<%= @client_token %>'
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          console.error(clientErr);
          return;
        }

        braintree.dataCollector.create({
          client: clientInstance,
          kount: true
        }, function (err, dataCollectorInstance) {
          if (err) {
            console.error(err);
            return;
          }
          var deviceData = dataCollectorInstance.deviceData;
          console.log(dataCollectorInstance);
          document.querySelector('#data_collector').value = deviceData;
        });

        console.log(clientInstance)

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14px'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
            number: {
              selector: '#card-number',
              placeholder: '4111 1111 1111 1111'
            },
            cvv: {
              selector: '#cvv',
              placeholder: '123'
            },
            expirationDate: {
              selector: '#expiration-date',
              placeholder: '10/2029'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            console.error(hostedFieldsErr);
            return;
          }
          console.log(hostedFieldsInstance);
          submit.removeAttribute('disabled');
          document.querySelector('#first_name').placeholder = 'First Name';
          document.querySelector('#last_name').placeholder = 'Last Name';
          document.querySelector('#email').placeholder = 'Email';
          document.querySelector('#postal_code').placeholder = 'Postal Code';

          form.addEventListener('submit', function (event) {
            event.preventDefault();
            console.log(event);
            submit.setAttribute('disabled', true);
            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }

              console.log(payload.nonce);
              console.log(payload.details.cardType);
              document.querySelector('#payment_method_nonce').value = payload.nonce;
              document.querySelector('#card_type').value = payload.details.cardType;
              form.submit();

            });
          }, false);
        });
      });
</script>

app/views/carts/index.html.erb
<h1>Summary Statistics</h1>

<!--Using Money gem to ensure correct formatting for currency amounts-->
<h2>Total Selected in Carts: <%= Money.from_amount(@carts.sum("amount"), "USD").format %></h2>

<!--Note that, because the amount isn't stored in "checkouts" until the txn is successful, the below is only summing the amounts of those successful txns.-->
<h2>Total Successfully Purchased: <%= Money.from_amount(@checkouts.sum("amount"), "USD").format %></h2>

<!--Number of successful transactions divided by total number of times an amount submitted on the "Cart" page-->
<h2>Cart Conversion Rate: <%= (@successfulCheckouts.length.to_f / @carts.length.to_f * 100).round(2) %>%</h2>

<h2>Average Amount Selected in Cart: <%= Money.from_amount(@carts.average("amount").round(2), "USD").format %></h2>

<h2>Average Completed Purchase: <%= Money.from_amount(@checkouts.average("amount").round(2), "USD").format %></h2>

<h1>All Checkouts</h1>

<!--Links to each checkout, labelled by submitted customer email address-->
<ul id="checkouts">
  <% @checkouts.each do |checkout| %>
    <li>
      <%= link_to checkout.email, cart_path(checkout.cart_id) %>
    </li>
  <% end %>
</ul>

app/views/carts/show.html.erb
<h1><%= @checkout.email %></h1>

<ul id="checkoutData">
    <li>
      First Name: <%= @checkout.first_name %>
    </li>
    <li>
      Last Name: <%= @checkout.last_name %>
    </li>
    <li>
      Postal Code: <%= @checkout.postal_code.to_i %>
    </li>
    <li>
      Customer ID: <%= @checkout.customer_id %>
    </li>
    <li>
      <!--Using Money gem to ensure correct formatting for currency amounts-->
      Amount: <%= Money.from_amount(@checkout.amount, "USD").format %>
    </li>
    <li>
      Card Type: <%= @checkout.card_type %>
    </li>
    <li>
      Transaction ID: <%= @checkout.transaction_id %>
    </li>
    <li>
      Transaction Result: <%= @checkout.transaction_result %>
    </li>
    <li>
      Verification ID: <%= @checkout.verification_id %>
    </li>
    <li>
      Verification Result: <%= @checkout.verification_result %>
    </li>
</ul>

<%= link_to "<< Back to Checkouts List", carts_path %>

app/views/checkouts/create.html.erb
<!--Payment confirmation or failure page, depending on outcome.-->
<div id="main_wrapper">
    <div id="checkout_container">
        <div id="title"><%= @title %></div>
        <!--Note that @link is an empty string if the payment is successful, so the link only shows on the payment failure page-->
        <div id="text"> <%= @message %><%= link_to @link, welcome_index_path %></div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBtApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="main_wrapper">
      <div id="welcome_container">
        <div id="title">Ready to Purchase?</div>
        <div id='form_container'>
          <form action="/carts" id="cart-form" method="post">
                <label for='amount'>Select Amount</label><br>
                <input type='number' step ="0.01" name='amount' class='welcome-field' id='amount' required><br>
                <input type="submit" value="Check Out" id='welcome-submit' disabled />
                <!--Line below required for Rails forms-->
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              </form>

        </div>
      </div>
  </div>

<script>

  var field = document.querySelector('input[type="number"]');
  var submit = document.querySelector('input[type="submit"]');
  var form = document.querySelector('#cart-form');

  field.addEventListener("input", () => {
    submit.removeAttribute('disabled');
  });

  field.placeholder = 'Purchase Amount';

  form.addEventListener('submit', function (event) {
    event.preventDefault();
    console.log(event);
    submit.setAttribute('disabled', true);
    if (field.value > 0) {
      form.submit();
    }
    else {
      alert("Hey, I'm trying to make some money here! Please enter a positive amount.")
    }
  });

</script>